In [2]:
import pandas as pd
import numpy as np

In [7]:
df = pd.read_excel(r'C:\Users\rbs\Downloads\transactions.xlsx')

In [6]:
pip install xlrd

Collecting xlrd
  Downloading https://files.pythonhosted.org/packages/b0/16/63576a1a001752e34bf8ea62e367997530dc553b689356b9879339cf45a4/xlrd-1.2.0-py2.py3-none-any.whl (103kB)
Installing collected packages: xlrd
Successfully installed xlrd-1.2.0
Note: you may need to restart the kernel to use updated packages.

In [8]:
df.head(100)

,#,Date,Month,Time (hrs),Customer ID,Income,Mortgage balance,Mortage payment,Utilities,Credit Card balance,Card payment,Other payment,Other payment type,Other payment amount
0,18121,25,12,17,1,7543,0,0.0,0.00,46260,754.3,False,None,0.0
1,21235,21,10,9,1,7543,0,0.0,0.00,46260,0.0,True,Insurance,312.0
2,24374,26,2,9,1,7543,0,0.0,0.00,46260,0.0,True,Entertainment,49.7
3,53803,18,8,19,1,7543,0,0.0,0.00,46260,0.0,True,Travel,171.0
4,82485,2,5,19,1,7543,0,0.0,0.00,46260,0.0,True,Retail,174.0
5,94329,9,11,11,1,7543,0,0.0,0.00,46260,0.0,True,Entertainment,53.2
6,95004,15,5,13,1,7543,0,0.0,0.00,46260,0.0,True,Entertainment,35.0
7,103590,28,4,13,1,7543,0,0.0,0.00,46260,0.0,True,Insurance,228.0
8,109136,21,6,15,1,7543,0,0.0,0.00,46260,0.0,True,Groceries,91.0
9,127712,9,8,11,1,7543,0,0.0,0.00,46260,0.0,True,Groceries,100.0
10,137958,8,5,11,1,7543,0,0.0,0.00,46260,0.0,True,Insurance,372.0
11,138020,15,12,10,1,7543,0,0.0,0.00,46260,754.3,False,None,0.0
12,138302,4,5,9,1,7543,0,0.0,0.00,46260,0.0,True,Insurance,348.0
13,141456,9,10,10,1,7543,0,0.0,0.00,46260,0.0,True,Retail,128.0
14,160815,27,12,10,1,7543,0,0.0,0.00,46260,0.0,True,Retail,144.0
15,162780,19,9,15,1,7543,0,0.0,0.00,46260,0.0,True,Groceries,70.0
16,172187,15,2,19,1,7543,0,0.0,0.00,46260,0.0,True,Retail,188.0
17,178429,25,1,18,1,7543,0,0.0,0.00,46260,0.0,True,Entertainment,58.1
18,194499,3,3,9,1,7543,0,0.0,0.00,46260,0.0,True,Transport,43.5
19,210822,12,7,17,1,7543,0,0.0,0.00,46260,0.0,True,Entertainment,49.0
20,211861,6,7,14,1,7543,0,0.0,0.00,46260,0.0,True,Groceries,92.0
21,255943,11,4,17,1,7543,0,0.0,0.00,46260,0.0,True,Travel,225.0
22,262515,1,10,19,1,7543,0,0.0,0.00,46260,0.0,True,Travel,294.0
23,270294,8,7,9,1,7543,0,0.0,0.00,46260,0.0,True,Insurance,396.0
24,276403,27,7,14,1,7543,0,0.0,905.16,46260,0.0,False,None,0.0
25,278905,1,1,16,1,7543,0,0.0,0.00,46260,0.0,True,Restaurant,42.4
26,288165,7,8,9,1,7543,0,0.0,0.00,46260,0.0,True,Travel,222.0
27,297300,28,7,15,1,7543,0,0.0,0.00,46260,754.3,False,None,0.0
28,314756,11,2,13,1,7543,0,0.0,0.00,46260,0.0,True,Restaurant,65.6
29,315595,26,8,10,1,7543,0,0.0,0.00,46260,0.0,True,Transport,25.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,331011,5,9,16,2,4044,0,0.0,0.00,0,0.0,True,Insurance,256.0
71,342966,26,8,14,2,4044,0,0.0,0.00,0,0.0,True,Entertainment,36.4
72,343570,4,6,17,2,4044,0,0.0,0.00,0,0.0,True,Entertainment,43.4
73,349220,8,7,12,2,4044,0,0.0,0.00,0,0.0,True,Restaurant,44.0
74,358346,14,3,16,2,4044,0,0.0,0.00,0,0.0,True,Insurance,360.0
75,372937,19,7,18,2,4044,0,0.0,0.00,0,0.0,True,Retail,118.0
76,377690,13,11,16,2,4044,0,0.0,0.00,0,0.0,True,Transport,49.0
77,384258,17,1,18,2,4044,0,0.0,0.00,0,0.0,True,Groceries,82.0
78,403534,17,3,12,2,4044,0,0.0,0.00,0,0.0,True,Retail,112.0
79,406548,7,10,15,2,4044,0,0.0,0.00,0,0.0,True,Groceries,52.0
80,416862,10,6,9,2,4044,0,0.0,0.00,0,0.0,True,Insurance,236.0
81,429885,20,3,17,2,4044,0,0.0,0.00,0,0.0,True,Travel,165.0
82,437017,20,1,11,2,4044,0,0.0,0.00,0,0.0,True,Transport,38.0
83,463546,16,4,17,2,4044,0,0.0,0.00,0,0.0,True,Entertainment,59.5
84,475843,18,7,17,2,4044,0,0.0,0.00,0,0.0,True,Restaurant,44.0
85,481839,11,7,11,2,4044,0,0.0,0.00,0,0.0,True,Travel,162.0
86,484337,12,1,18,2,4044,0,0.0,0.00,0,0.0,True,Travel,195.0
87,488131,5,11,17,2,4044,0,0.0,0.00,0,0.0,True,Transport,25.5
88,491709,8,12,14,2,4044,0,0.0,0.00,0,0.0,True,Insurance,256.0
89,497125,4,9,17,2,4044,0,0.0,0.00,0,0.0,True,Groceries,80.0
90,14497,15,9,11,3,818,0,0.0,0.00,19764,81.8,False,None,0.0
91,26131,19,8,17,3,818,0,0.0,0.00,19764,0.0,True,Insurance,324.0
92,35669,27,5,19,3,818,0,0.0,0.00,19764,0.0,True,Travel,195.0
93,38561,22,4,16,3,818,0,0.0,0.00,19764,0.0,True,Transport,29.5
94,41545,11,1,19,3,818,0,0.0,0.00,19764,0.0,True,Travel,255.0
95,52854,9,8,13,3,818,0,0.0,114.52,19764,0.0,False,None,0.0
96,74522,20,5,10,3,818,0,0.0,0.00,19764,0.0,True,Groceries,92.0
97,77431,26,5,16,3,818,0,0.0,0.00,19764,0.0,True,Entertainment,39.9
98,82632,5,1,12,3,818,0,0.0,0.00,19764,0.0,True,Insurance,376.0
99,92088,13,6,18,3,818,0,0.0,0.00,19764,0.0,True,Retail,118.0

In [56]:
df.sort_values(by=['Customer ID', 'Month', 'Date', 'Time (hrs)'],ascending=[True,True,True,True])

,#,Date,Month,Time (hrs),Customer ID,Income,Mortgage balance,Mortage payment,Utilities,Credit Card balance,Card payment,Other payment,Other payment type,Other payment amount
25,278905,1,1,16,1,7543,0,0.0,0.00,46260,0.0,True,Restaurant,42.4
31,354278,9,1,13,1,7543,0,0.0,0.00,46260,0.0,True,Transport,40.5
17,178429,25,1,18,1,7543,0,0.0,0.00,46260,0.0,True,Entertainment,58.1
28,314756,11,2,13,1,7543,0,0.0,0.00,46260,0.0,True,Restaurant,65.6
44,478338,13,2,12,1,7543,0,0.0,0.00,46260,0.0,True,Transport,50.0
16,172187,15,2,19,1,7543,0,0.0,0.00,46260,0.0,True,Retail,188.0
42,434581,22,2,9,1,7543,0,0.0,0.00,46260,754.3,False,None,0.0
2,24374,26,2,9,1,7543,0,0.0,0.00,46260,0.0,True,Entertainment,49.7
18,194499,3,3,9,1,7543,0,0.0,0.00,46260,0.0,True,Transport,43.5
35,391057,9,3,17,1,7543,0,0.0,0.00,46260,0.0,True,Transport,45.5
21,255943,11,4,17,1,7543,0,0.0,0.00,46260,0.0,True,Travel,225.0
7,103590,28,4,13,1,7543,0,0.0,0.00,46260,0.0,True,Insurance,228.0
4,82485,2,5,19,1,7543,0,0.0,0.00,46260,0.0,True,Retail,174.0
12,138302,4,5,9,1,7543,0,0.0,0.00,46260,0.0,True,Insurance,348.0
10,137958,8,5,11,1,7543,0,0.0,0.00,46260,0.0,True,Insurance,372.0
45,479294,14,5,14,1,7543,0,0.0,0.00,46260,0.0,True,Retail,126.0
6,95004,15,5,13,1,7543,0,0.0,0.00,46260,0.0,True,Entertainment,35.0
30,341742,18,5,11,1,7543,0,0.0,0.00,46260,0.0,True,Transport,45.0
47,489072,20,5,9,1,7543,0,0.0,829.73,46260,0.0,False,None,0.0
38,401865,6,6,17,1,7543,0,0.0,0.00,46260,0.0,True,Restaurant,46.4
37,398494,14,6,10,1,7543,0,0.0,0.00,46260,0.0,True,Retail,170.0
8,109136,21,6,15,1,7543,0,0.0,0.00,46260,0.0,True,Groceries,91.0
20,211861,6,7,14,1,7543,0,0.0,0.00,46260,0.0,True,Groceries,92.0
23,270294,8,7,9,1,7543,0,0.0,0.00,46260,0.0,True,Insurance,396.0
34,380346,9,7,13,1,7543,0,0.0,0.00,46260,0.0,True,Retail,112.0
19,210822,12,7,17,1,7543,0,0.0,0.00,46260,0.0,True,Entertainment,49.0
24,276403,27,7,14,1,7543,0,0.0,905.16,46260,0.0,False,None,0.0
27,297300,28,7,15,1,7543,0,0.0,0.00,46260,754.3,False,None,0.0
26,288165,7,8,9,1,7543,0,0.0,0.00,46260,0.0,True,Travel,222.0
9,127712,9,8,11,1,7543,0,0.0,0.00,46260,0.0,True,Groceries,100.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
499968,152929,22,6,17,10000,1004,0,0.0,0.00,2880,0.0,True,Entertainment,58.1
499997,473032,23,6,14,10000,1004,0,0.0,0.00,2880,0.0,True,Groceries,92.0
499982,305420,25,6,15,10000,1004,0,0.0,0.00,2880,0.0,True,Retail,186.0
499967,144472,26,6,9,10000,1004,0,0.0,0.00,2880,0.0,True,Groceries,91.0
499987,382106,6,7,17,10000,1004,0,0.0,0.00,2880,0.0,True,Transport,42.0
499979,288575,13,7,13,10000,1004,0,0.0,0.00,2880,100.4,False,None,0.0
499998,488970,15,7,16,10000,1004,0,0.0,0.00,2880,0.0,True,Transport,30.0
499954,18719,18,7,14,10000,1004,0,0.0,0.00,2880,0.0,True,Travel,168.0
499970,160360,21,7,13,10000,1004,0,0.0,0.00,2880,0.0,True,Restaurant,61.6
499953,17414,27,7,17,10000,1004,0,0.0,0.00,2880,0.0,True,Groceries,60.0
499995,461076,5,8,18,10000,1004,0,0.0,0.00,2880,0.0,True,Transport,41.0
499958,49854,16,8,19,10000,1004,0,0.0,0.00,2880,0.0,True,Insurance,276.0
499966,117769,9,9,11,10000,1004,0,0.0,0.00,2880,0.0,True,Travel,198.0
499955,24491,11,9,15,10000,1004,0,0.0,0.00,2880,100.4,False,None,0.0
499963,84831,11,9,19,10000,1004,0,0.0,0.00,2880,0.0,True,Travel,162.0
499961,73229,17,9,19,10000,1004,0,0.0,0.00,2880,0.0,True,Retail,188.0
499994,455645,19,9,10,10000,1004,0,0.0,150.60,2880,0.0,False,None,0.0
499992,417223,1,10,17,10000,1004,0,0.0,150.60,2880,0.0,False,None,0.0
499960,63100,3,10,18,10000,1004,0,0.0,0.00,2880,0.0,True,Retail,162.0
499978,287191,10,10,17,10000,1004,0,0.0,0.00,2880,0.0,True,Entertainment,46.9
499974,194197,11,10,17,10000,1004,0,0.0,0.00,2880,100.4,False,None,0.0
499964,101459,28,10,18,10000,1004,0,0.0,0.00,2880,0.0,True,Insurance,200.0
499956,24554,2,11,14,10000,1004,0,0.0,0.00,2880,0.0,True,Transport,49.0
499977,255915,6,11,19,10000,1004,0,0.0,0.00,2880,0.0,True,Restaurant,40.8
499991,410763,13,11,10,10000,1004,0,0.0,0.00,2880,0.0,True,Entertainment,51.8
499981,297989,21,11,18,10000,1004,0,0.0,0.00,2880,0.0,True,Retail,106.0
499952,15609,27,11,18,10000,1004,0,0.0,0.00,2880,0.0,True,Restaurant,63.2
499951,6751,10,12,10,10000,1004,0,0.0,0.00,2880,0.0,True,Retail,158.0
499972,178074,14,12,15,10000,1004,0,0.0,0.00,2880,0.0,True,Retail,112.0
499984,309948,24,12,9,10000,1004,0,0.0,0.00,2880,0.0,True,Restaurant,52.8

In [9]:
conda install -c conda-forge tsfresh

Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... failed with current_repodata.json, will retry with next repodata source.
Initial quick solve with frozen env failed.  Unfreezing env and trying again.
Solving environment: ...working... failed with current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: C:\Users\rbs\Anaconda3\envs\test1

  added / updated specs:
    - tsfresh


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    asn1crypto-0.24.0          |        py37_1003         154 KB  conda-forge
    ca-certificates-2019.6.16  |       hecc5488_0         183 KB  conda-forge
    certifi-2019.6.16          |           py37_1         149 KB  conda-forge
    cffi-1.12.3                |   py37hb32ad35_0         219 KB  conda-forge
    chardet-3.0.4              |        py37_1003         184 KB  conda-forge
    cryptography-2.7           |   py37hb32ad35_0         551 KB  conda-forge
    future-0.17.1              |        py37_1000         697 KB  conda-forge
    idna-2.8                   |        py37_1000         100 KB  conda-forge
    joblib-0.13.2              |             py_0         180 KB  conda-forge
    libblas-3.8.0              |           11_mkl         3.5 MB  conda-forge
    libcblas-3.8.0             |           11_mkl         3.5 MB  conda-forge
    mkl-service-2.1.0          |   py37hfa6e2cd_0          51 KB  conda-forge
    openssl-1.1.1c             |       hfa6e2cd_0         4.7 MB  conda-forge
    patsy-0.5.1                |             py_0         187 KB  conda-forge
    pycparser-2.19             |           py37_1         171 KB  conda-forge
    pyopenssl-19.0.0           |           py37_0          81 KB  conda-forge
    pysocks-1.7.0              |           py37_0          26 KB  conda-forge
    requests-2.22.0            |           py37_1          84 KB  conda-forge
    scikit-learn-0.21.3        |   py37h7208079_0         5.7 MB  conda-forge
    scipy-1.3.0                |   py37h29ff71c_0        14.3 MB
    statsmodels-0.10.1         |   py37hfa6e2cd_0         8.8 MB  conda-forge
    tqdm-4.33.0                |             py_0          41 KB  conda-forge
    tsfresh-0.11.2             |             py_0          77 KB  conda-forge
    urllib3-1.25.3             |           py37_0         187 KB  conda-forge
    win_inet_pton-1.1.0        |           py37_0           7 KB  conda-forge
    ------------------------------------------------------------
                                           Total:        43.9 MB

The following NEW packages will be INSTALLED:

  asn1crypto         conda-forge/win-64::asn1crypto-0.24.0-py37_1003
  cffi               conda-forge/win-64::cffi-1.12.3-py37hb32ad35_0
  chardet            conda-forge/win-64::chardet-3.0.4-py37_1003
  cryptography       conda-forge/win-64::cryptography-2.7-py37hb32ad35_0
  future             conda-forge/win-64::future-0.17.1-py37_1000
  idna               conda-forge/win-64::idna-2.8-py37_1000
  joblib             conda-forge/noarch::joblib-0.13.2-py_0
  libblas            conda-forge/win-64::libblas-3.8.0-11_mkl
  libcblas           conda-forge/win-64::libcblas-3.8.0-11_mkl
  mkl-service        conda-forge/win-64::mkl-service-2.1.0-py37hfa6e2cd_0
  patsy              conda-forge/noarch::patsy-0.5.1-py_0
  pycparser          conda-forge/win-64::pycparser-2.19-py37_1
  pyopenssl          conda-forge/win-64::pyopenssl-19.0.0-py37_0
  pysocks            conda-forge/win-64::pysocks-1.7.0-py37_0
  requests           conda-forge/win-64::requests-2.22.0-py37_1
  scikit-learn       conda-forge/win-64::scikit-learn-0.21.3-py37h7208079_0
  scipy              pkgs/main/win-64::scipy-1.3.0-py37h29ff71c_0
  statsmodels        conda-forge/win-64::statsmodels-0.10.1-py37hfa6e2cd_0
  tqdm               conda-forge/noarch::tqdm-4.33.0-py_0
  tsfresh            conda-forge/noarch::tsfresh-0.11.2-py_0
  urllib3            conda-forge/win-64::urllib3-1.25.3-py37_0
  win_inet_pton      conda-forge/win-64::win_inet_pton-1.1.0-py37_0

The following packages will be UPDATED:

  ca-certificates    pkgs/main::ca-certificates-2019.5.15-1 --> conda-forge::ca-certificates-2019.6.16-hecc5488_0

The following packages will be SUPERSEDED by a higher-priority channel:

  certifi                                         pkgs/main --> conda-forge
  openssl              pkgs/main::openssl-1.1.1c-he774522_1 --> conda-forge::openssl-1.1.1c-hfa6e2cd_0



Downloading and Extracting Packages

ca-certificates-2019 | 183 KB    |            |   0%
ca-certificates-2019 | 183 KB    | 8          |   9%
ca-certificates-2019 | 183 KB    | ########## | 100%

libcblas-3.8.0       | 3.5 MB    |            |   0%
libcblas-3.8.0       | 3.5 MB    | 7          |   8%
libcblas-3.8.0       | 3.5 MB    | ###2       |  32%
libcblas-3.8.0       | 3.5 MB    | ######3    |  64%
libcblas-3.8.0       | 3.5 MB    | #########5 |  95%
libcblas-3.8.0       | 3.5 MB    | ########## | 100%

tsfresh-0.11.2       | 77 KB     |            |   0%
tsfresh-0.11.2       | 77 KB     | ########## | 100%

cryptography-2.7     | 551 KB    |            |   0%
cryptography-2.7     | 551 KB    | #########2 |  93%
cryptography-2.7     | 551 KB    | ########## | 100%

future-0.17.1        | 697 KB    |            |   0%
future-0.17.1        | 697 KB    | #######3   |  73%
future-0.17.1        | 697 KB    | ########## | 100%

patsy-0.5.1          | 187 KB    |            |   0%
patsy-0.5.1          | 187 KB    | ########## | 100%

cffi-1.12.3          | 219 KB    |            |   0%
cffi-1.12.3          | 219 KB    | ########## | 100%

requests-2.22.0      | 84 KB     |            |   0%
requests-2.22.0      | 84 KB     | #9         |  19%
requests-2.22.0      | 84 KB     | ########## | 100%

chardet-3.0.4        | 184 KB    |            |   0%
chardet-3.0.4        | 184 KB    | ########## | 100%

win_inet_pton-1.1.0  | 7 KB      |            |   0%
win_inet_pton-1.1.0  | 7 KB      | ########## | 100%

openssl-1.1.1c       | 4.7 MB    |            |   0%
openssl-1.1.1c       | 4.7 MB    | #1         |  11%
openssl-1.1.1c       | 4.7 MB    | ##9        |  29%
openssl-1.1.1c       | 4.7 MB    | #####1     |  52%
openssl-1.1.1c       | 4.7 MB    | #######5   |  75%
openssl-1.1.1c       | 4.7 MB    | #########9 |  99%
openssl-1.1.1c       | 4.7 MB    | ########## | 100%

pycparser-2.19       | 171 KB    |            |   0%
pycparser-2.19       | 171 KB    | ########## | 100%

scipy-1.3.0          | 14.3 MB   |            |   0%
scipy-1.3.0          | 14.3 MB   |            |   1%
scipy-1.3.0          | 14.3 MB   | 8          |   8%
scipy-1.3.0          | 14.3 MB   | #5         |  16%
scipy-1.3.0          | 14.3 MB   | ##3        |  24%
scipy-1.3.0          | 14.3 MB   | ##9        |  30%
scipy-1.3.0          | 14.3 MB   | ###7       |  38%
scipy-1.3.0          | 14.3 MB   | ####5      |  45%
scipy-1.3.0          | 14.3 MB   | #####3     |  53%
scipy-1.3.0          | 14.3 MB   | ######1    |  61%
scipy-1.3.0          | 14.3 MB   | ######8    |  69%
scipy-1.3.0          | 14.3 MB   | #######6   |  77%
scipy-1.3.0          | 14.3 MB   | ########4  |  85%
scipy-1.3.0          | 14.3 MB   | #########2 |  93%
scipy-1.3.0          | 14.3 MB   | ########## | 100%

libblas-3.8.0        | 3.5 MB    |            |   0%
libblas-3.8.0        | 3.5 MB    | #3         |  14%
libblas-3.8.0        | 3.5 MB    | ####6      |  46%
libblas-3.8.0        | 3.5 MB    | #######7   |  78%
libblas-3.8.0        | 3.5 MB    | ########## | 100%

tqdm-4.33.0          | 41 KB     |            |   0%
tqdm-4.33.0          | 41 KB     | ########## | 100%

certifi-2019.6.16    | 149 KB    |            |   0%
certifi-2019.6.16    | 149 KB    | ########## | 100%

pysocks-1.7.0        | 26 KB     |            |   0%
pysocks-1.7.0        | 26 KB     | ########## | 100%

scikit-learn-0.21.3  | 5.7 MB    |            |   0%
scikit-learn-0.21.3  | 5.7 MB    | 8          |   9%
scikit-learn-0.21.3  | 5.7 MB    | ##8        |  29%
scikit-learn-0.21.3  | 5.7 MB    | ####8      |  48%
scikit-learn-0.21.3  | 5.7 MB    | ######8    |  68%
scikit-learn-0.21.3  | 5.7 MB    | ########8  |  88%
scikit-learn-0.21.3  | 5.7 MB    | ########## | 100%

idna-2.8             | 100 KB    |            |   0%
idna-2.8             | 100 KB    | ########## | 100%

mkl-service-2.1.0    | 51 KB     |            |   0%
mkl-service-2.1.0    | 51 KB     | ########## | 100%

joblib-0.13.2        | 180 KB    |            |   0%
joblib-0.13.2        | 180 KB    | ########## | 100%

urllib3-1.25.3       | 187 KB    |            |   0%
urllib3-1.25.3       | 187 KB    | ########## | 100%

pyopenssl-19.0.0     | 81 KB     |            |   0%
pyopenssl-19.0.0     | 81 KB     | ########## | 100%

statsmodels-0.10.1   | 8.8 MB    |            |   0%
statsmodels-0.10.1   | 8.8 MB    | 5          |   5%
statsmodels-0.10.1   | 8.8 MB    | #8         |  18%
statsmodels-0.10.1   | 8.8 MB    | ###        |  31%
statsmodels-0.10.1   | 8.8 MB    | ####3      |  44%
statsmodels-0.10.1   | 8.8 MB    | #####6     |  56%
statsmodels-0.10.1   | 8.8 MB    | ######9    |  69%
statsmodels-0.10.1   | 8.8 MB    | ########2  |  82%
statsmodels-0.10.1   | 8.8 MB    | #########5 |  95%
statsmodels-0.10.1   | 8.8 MB    | ########## | 100%

asn1crypto-0.24.0    | 154 KB    |            |   0%
asn1crypto-0.24.0    | 154 KB    | ########## | 100%
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done

Note: you may need to restart the kernel to use updated packages.

==> WARNING: A newer version of conda exists. <==
  current version: 4.7.10
  latest version: 4.7.11

Please update conda by running

    $ conda update -n base -c defaults conda

In [10]:
conda update -n base -c defaults conda

Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: C:\Users\rbs\Anaconda3

  added / updated specs:
    - conda


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-4.7.11               |           py37_0         3.0 MB
    ------------------------------------------------------------
                                           Total:         3.0 MB

The following packages will be UPDATED:

  conda                                       4.7.10-py37_0 --> 4.7.11-py37_0



Downloading and Extracting Packages

conda-4.7.11         | 3.0 MB    |            |   0%
conda-4.7.11         | 3.0 MB    | 6          |   7%
conda-4.7.11         | 3.0 MB    | ####3      |  44%
conda-4.7.11         | 3.0 MB    | ########1  |  82%
conda-4.7.11         | 3.0 MB    | ########## | 100%
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done

Note: you may need to restart the kernel to use updated packages.

In [11]:
import tsfresh

In [75]:
# # df1['Date']+ ':' + df1['Month'] + df['Time (hrs)']
# # m=df['Time (hrs)'].apply(str)+':00:00'
# pd.to_datetime(df2['Date'].apply(str) + ':' + df2['Month'].apply(str) + '2018')

In [57]:
df2 = df[:1046]

In [61]:
label = df2['Mortgage balance']

In [62]:
label

0            0
1            0
2            0
3            0
4            0
         ...
1041    124092
1042    124092
1043    124092
1044    124092
1045    124092
Name: Mortgage balance, Length: 1046, dtype: int64

In [70]:
df2 = df2.drop(['#','Date', 'Month', 'Time (hrs)', 'Other payment', 'Mortgage balance', 'Other payment type'], axis=1)

In [38]:
from tsfresh.utilities.dataframe_functions import impute
from tsfresh import extract_features, extract_relevant_features, select_features


# features = impute(features)

In [71]:
df2

,Customer ID,Income,Mortage payment,Utilities,Credit Card balance,Card payment,Other payment amount
0,1,7543,0.00,0.00,46260,754.3,0.0
1,1,7543,0.00,0.00,46260,0.0,312.0
2,1,7543,0.00,0.00,46260,0.0,49.7
3,1,7543,0.00,0.00,46260,0.0,171.0
4,1,7543,0.00,0.00,46260,0.0,174.0
5,1,7543,0.00,0.00,46260,0.0,53.2
6,1,7543,0.00,0.00,46260,0.0,35.0
7,1,7543,0.00,0.00,46260,0.0,228.0
8,1,7543,0.00,0.00,46260,0.0,91.0
9,1,7543,0.00,0.00,46260,0.0,100.0
10,1,7543,0.00,0.00,46260,0.0,372.0
11,1,7543,0.00,0.00,46260,754.3,0.0
12,1,7543,0.00,0.00,46260,0.0,348.0
13,1,7543,0.00,0.00,46260,0.0,128.0
14,1,7543,0.00,0.00,46260,0.0,144.0
15,1,7543,0.00,0.00,46260,0.0,70.0
16,1,7543,0.00,0.00,46260,0.0,188.0
17,1,7543,0.00,0.00,46260,0.0,58.1
18,1,7543,0.00,0.00,46260,0.0,43.5
19,1,7543,0.00,0.00,46260,0.0,49.0
20,1,7543,0.00,0.00,46260,0.0,92.0
21,1,7543,0.00,0.00,46260,0.0,225.0
22,1,7543,0.00,0.00,46260,0.0,294.0
23,1,7543,0.00,0.00,46260,0.0,396.0
24,1,7543,0.00,905.16,46260,0.0,0.0
25,1,7543,0.00,0.00,46260,0.0,42.4
26,1,7543,0.00,0.00,46260,0.0,222.0
27,1,7543,0.00,0.00,46260,754.3,0.0
28,1,7543,0.00,0.00,46260,0.0,65.6
29,1,7543,0.00,0.00,46260,0.0,25.0
...,...,...,...,...,...,...,...
1016,20,4596,0.00,0.00,44240,0.0,44.0
1017,20,4596,0.00,0.00,44240,0.0,79.0
1018,20,4596,1240.92,0.00,44240,0.0,0.0
1019,20,4596,0.00,505.56,44240,0.0,0.0
1020,20,4596,0.00,0.00,44240,0.0,47.2
1021,20,4596,1240.92,0.00,44240,0.0,0.0
1022,20,4596,1240.92,0.00,44240,0.0,0.0
1023,20,4596,0.00,0.00,44240,0.0,42.4
1024,20,4596,1240.92,0.00,44240,0.0,0.0
1025,20,4596,0.00,0.00,44240,0.0,72.0
1026,20,4596,0.00,0.00,44240,0.0,27.0
1027,20,4596,0.00,0.00,44240,0.0,154.0
1028,20,4596,0.00,0.00,44240,0.0,46.2
1029,20,4596,0.00,0.00,44240,0.0,388.0
1030,20,4596,0.00,0.00,44240,0.0,270.0
1031,20,4596,0.00,643.44,44240,0.0,0.0
1032,20,4596,0.00,0.00,44240,0.0,116.0
1033,20,4596,0.00,0.00,44240,0.0,178.0
1034,20,4596,0.00,0.00,44240,0.0,41.5
1035,20,4596,0.00,597.48,44240,0.0,0.0
1036,20,4596,0.00,0.00,44240,0.0,26.0
1037,20,4596,0.00,0.00,44240,0.0,102.0
1038,20,4596,0.00,0.00,44240,0.0,64.8
1039,20,4596,1240.92,0.00,44240,0.0,0.0
1040,20,4596,0.00,0.00,44240,0.0,44.0
1041,20,4596,1240.92,0.00,44240,0.0,0.0
1042,20,4596,0.00,0.00,44240,0.0,285.0
1043,20,4596,0.00,0.00,44240,0.0,152.0
1044,20,4596,0.00,0.00,44240,0.0,41.6
1045,20,4596,0.00,0.00,44240,0.0,59.5

In [72]:
df2.apply(pd.to_numeric)

,Customer ID,Income,Mortage payment,Utilities,Credit Card balance,Card payment,Other payment amount
0,1,7543,0.00,0.00,46260,754.3,0.0
1,1,7543,0.00,0.00,46260,0.0,312.0
2,1,7543,0.00,0.00,46260,0.0,49.7
3,1,7543,0.00,0.00,46260,0.0,171.0
4,1,7543,0.00,0.00,46260,0.0,174.0
5,1,7543,0.00,0.00,46260,0.0,53.2
6,1,7543,0.00,0.00,46260,0.0,35.0
7,1,7543,0.00,0.00,46260,0.0,228.0
8,1,7543,0.00,0.00,46260,0.0,91.0
9,1,7543,0.00,0.00,46260,0.0,100.0
10,1,7543,0.00,0.00,46260,0.0,372.0
11,1,7543,0.00,0.00,46260,754.3,0.0
12,1,7543,0.00,0.00,46260,0.0,348.0
13,1,7543,0.00,0.00,46260,0.0,128.0
14,1,7543,0.00,0.00,46260,0.0,144.0
15,1,7543,0.00,0.00,46260,0.0,70.0
16,1,7543,0.00,0.00,46260,0.0,188.0
17,1,7543,0.00,0.00,46260,0.0,58.1
18,1,7543,0.00,0.00,46260,0.0,43.5
19,1,7543,0.00,0.00,46260,0.0,49.0
20,1,7543,0.00,0.00,46260,0.0,92.0
21,1,7543,0.00,0.00,46260,0.0,225.0
22,1,7543,0.00,0.00,46260,0.0,294.0
23,1,7543,0.00,0.00,46260,0.0,396.0
24,1,7543,0.00,905.16,46260,0.0,0.0
25,1,7543,0.00,0.00,46260,0.0,42.4
26,1,7543,0.00,0.00,46260,0.0,222.0
27,1,7543,0.00,0.00,46260,754.3,0.0
28,1,7543,0.00,0.00,46260,0.0,65.6
29,1,7543,0.00,0.00,46260,0.0,25.0
...,...,...,...,...,...,...,...
1016,20,4596,0.00,0.00,44240,0.0,44.0
1017,20,4596,0.00,0.00,44240,0.0,79.0
1018,20,4596,1240.92,0.00,44240,0.0,0.0
1019,20,4596,0.00,505.56,44240,0.0,0.0
1020,20,4596,0.00,0.00,44240,0.0,47.2
1021,20,4596,1240.92,0.00,44240,0.0,0.0
1022,20,4596,1240.92,0.00,44240,0.0,0.0
1023,20,4596,0.00,0.00,44240,0.0,42.4
1024,20,4596,1240.92,0.00,44240,0.0,0.0
1025,20,4596,0.00,0.00,44240,0.0,72.0
1026,20,4596,0.00,0.00,44240,0.0,27.0
1027,20,4596,0.00,0.00,44240,0.0,154.0
1028,20,4596,0.00,0.00,44240,0.0,46.2
1029,20,4596,0.00,0.00,44240,0.0,388.0
1030,20,4596,0.00,0.00,44240,0.0,270.0
1031,20,4596,0.00,643.44,44240,0.0,0.0
1032,20,4596,0.00,0.00,44240,0.0,116.0
1033,20,4596,0.00,0.00,44240,0.0,178.0
1034,20,4596,0.00,0.00,44240,0.0,41.5
1035,20,4596,0.00,597.48,44240,0.0,0.0
1036,20,4596,0.00,0.00,44240,0.0,26.0
1037,20,4596,0.00,0.00,44240,0.0,102.0
1038,20,4596,0.00,0.00,44240,0.0,64.8
1039,20,4596,1240.92,0.00,44240,0.0,0.0
1040,20,4596,0.00,0.00,44240,0.0,44.0
1041,20,4596,1240.92,0.00,44240,0.0,0.0
1042,20,4596,0.00,0.00,44240,0.0,285.0
1043,20,4596,0.00,0.00,44240,0.0,152.0
1044,20,4596,0.00,0.00,44240,0.0,41.6
1045,20,4596,0.00,0.00,44240,0.0,59.5

In [73]:
features = extract_features(df2,  column_id='Customer ID')         ## dataset needs a column id to be there

Feature Extraction:   0%|          | 0/5 [00:00<?, ?it/s]




Feature Extraction:  20%|██        | 1/5 [00:04<00:19,  4.76s/it]




Feature Extraction:  40%|████      | 2/5 [00:08<00:12,  4.31s/it]




Feature Extraction:  60%|██████    | 3/5 [00:11<00:08,  4.09s/it]




Feature Extraction:  80%|████████  | 4/5 [00:15<00:03,  3.95s/it]




Feature Extraction: 100%|██████████| 5/5 [00:18<00:00,  3.85s/it]

In [74]:
features

variable,Card payment__abs_energy,Card payment__absolute_sum_of_changes,"Card payment__agg_autocorrelation__f_agg_""mean""__maxlag_40","Card payment__agg_autocorrelation__f_agg_""median""__maxlag_40","Card payment__agg_autocorrelation__f_agg_""var""__maxlag_40","Card payment__agg_linear_trend__f_agg_""max""__chunk_len_10__attr_""intercept""","Card payment__agg_linear_trend__f_agg_""max""__chunk_len_10__attr_""rvalue""","Card payment__agg_linear_trend__f_agg_""max""__chunk_len_10__attr_""slope""","Card payment__agg_linear_trend__f_agg_""max""__chunk_len_10__attr_""stderr""","Card payment__agg_linear_trend__f_agg_""max""__chunk_len_50__attr_""intercept""",...,Utilities__symmetry_looking__r_0.9,Utilities__symmetry_looking__r_0.9500000000000001,Utilities__time_reversal_asymmetry_statistic__lag_1,Utilities__time_reversal_asymmetry_statistic__lag_2,Utilities__time_reversal_asymmetry_statistic__lag_3,Utilities__value_count__value_-1,Utilities__value_count__value_0,Utilities__value_count__value_1,Utilities__variance,Utilities__variance_larger_than_standard_deviation
id,,,,,,,,,,,,,,,,,,,,,
1,2.275874e+06,5280.10,-0.032620,-0.081992,0.032785,754.300000,-0.353553,-75.430000,115.221228,NaN,...,1.0,1.0,0.000000,0.000000e+00,0.000000,0.0,46.0,0.0,30105.446448,1.0
2,0.000000e+00,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,...,0.0,0.0,0.000000,0.000000e+00,0.000000,0.0,42.0,0.0,0.000000,0.0
3,3.345620e+04,736.20,-0.014780,-0.079622,0.021975,84.721429,-0.474342,-8.764286,7.274298,81.80,...,1.0,1.0,0.000000,-7.077717e+03,0.000000,0.0,53.0,0.0,1213.422604,1.0
4,0.000000e+00,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,...,1.0,1.0,0.000000,0.000000e+00,0.000000,0.0,33.0,0.0,12436.737122,1.0
5,1.668961e+06,6303.28,-0.000992,-0.100754,0.047146,363.488571,0.236351,27.460571,56.446830,558.80,...,1.0,1.0,0.000000,-7.755087e+05,0.000000,0.0,54.0,0.0,23318.130649,1.0
6,0.000000e+00,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,...,1.0,1.0,0.000000,0.000000e+00,0.000000,0.0,45.0,0.0,2996.817140,1.0
7,6.146560e+03,305.76,-0.018481,-0.035415,0.028704,25.872000,-0.124568,-1.176000,5.408085,NaN,...,0.0,0.0,0.000000,0.000000e+00,0.000000,0.0,47.0,0.0,0.000000,0.0
8,0.000000e+00,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,...,1.0,1.0,-633.572140,0.000000e+00,0.000000,0.0,44.0,0.0,176.153011,1.0
9,3.505602e+05,2201.76,-0.007936,-0.059934,0.023682,184.075714,-0.112253,-8.935714,35.374596,450.36,...,1.0,1.0,0.000000,0.000000e+00,0.000000,0.0,62.0,0.0,3587.105991,1.0
10,2.404118e+04,421.68,-0.016450,-0.040669,0.015731,48.048571,-0.167487,-5.163429,15.196662,135.54,...,1.0,1.0,0.000000,0.000000e+00,0.000000,0.0,51.0,0.0,14669.721600,1.0
11,0.000000e+00,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,...,1.0,1.0,0.000000,9.899815e+04,260837.243007,0.0,59.0,0.0,10443.904420,1.0
12,0.000000e+00,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,...,1.0,1.0,0.000000,-1.480918e+04,39024.183405,0.0,37.0,0.0,3830.687591,1.0
13,0.000000e+00,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,...,1.0,1.0,0.000000,0.000000e+00,0.000000,0.0,48.0,0.0,23525.133697,1.0
14,0.000000e+00,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,...,1.0,1.0,854.505194,0.000000e+00,-3246.478459,0.0,41.0,0.0,720.267854,1.0
15,0.000000e+00,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,...,1.0,1.0,0.000000,0.000000e+00,0.000000,0.0,47.0,0.0,18.921394,1.0
16,2.240423e+06,5952.18,-0.030601,-0.078205,0.017195,948.840000,-0.866025,-237.210000,79.070000,NaN,...,1.0,1.0,0.000000,0.000000e+00,0.000000,0.0,45.0,0.0,76800.667289,1.0
17,1.162145e+06,3112.00,-0.012174,-0.046046,0.016221,-88.914286,0.632456,88.914286,48.700360,622.40,...,1.0,1.0,0.000000,0.000000e+00,0.000000,0.0,64.0,0.0,28463.800338,1.0
18,0.000000e+00,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,...,1.0,1.0,0.000000,1.788426e+06,0.000000,0.0,66.0,0.0,47573.132544,1.0
19,1.302488e+05,721.80,-0.019349,-0.016543,0.000216,189.042857,-0.654654,-51.557143,29.766530,360.90,...,1.0,1.0,0.000000,0.000000e+00,540078.076291,0.0,51.0,0.0,8730.240636,1.0
20,2.112322e+05,919.20,-0.023230,-0.023485,0.000283,183.840000,-0.353553,-45.960000,70.205060,NaN,...,1.0,1.0,0.000000,0.000000e+00,0.000000,0.0,47.0,0.0,19311.688996,1.0

In [76]:
impute_extracted=impute(features)

C:\Users\rbs\Anaconda3\envs\test1\lib\site-packages\tsfresh\utilities\dataframe_functions.py:164: FutureWarning: The 'get_values' method is deprecated and will be removed in a future version. Use '.values' or 'np.asarray(..)' instead.
  data = df.get_values()
WARNING:tsfresh.utilities.dataframe_functions:The columns ['Card payment__fft_coefficient__coeff_36__attr_"abs"'
 'Card payment__fft_coefficient__coeff_36__attr_"angle"'
 'Card payment__fft_coefficient__coeff_36__attr_"imag"' ...
 'Utilities__friedrich_coefficients__m_3__r_30__coeff_2'
 'Utilities__friedrich_coefficients__m_3__r_30__coeff_3'
 'Utilities__max_langevin_fixed_point__m_3__r_30'] did not have any finite values. Filling with zeros.

In [77]:
impute_extracted

variable,Card payment__abs_energy,Card payment__absolute_sum_of_changes,"Card payment__agg_autocorrelation__f_agg_""mean""__maxlag_40","Card payment__agg_autocorrelation__f_agg_""median""__maxlag_40","Card payment__agg_autocorrelation__f_agg_""var""__maxlag_40","Card payment__agg_linear_trend__f_agg_""max""__chunk_len_10__attr_""intercept""","Card payment__agg_linear_trend__f_agg_""max""__chunk_len_10__attr_""rvalue""","Card payment__agg_linear_trend__f_agg_""max""__chunk_len_10__attr_""slope""","Card payment__agg_linear_trend__f_agg_""max""__chunk_len_10__attr_""stderr""","Card payment__agg_linear_trend__f_agg_""max""__chunk_len_50__attr_""intercept""",...,Utilities__symmetry_looking__r_0.9,Utilities__symmetry_looking__r_0.9500000000000001,Utilities__time_reversal_asymmetry_statistic__lag_1,Utilities__time_reversal_asymmetry_statistic__lag_2,Utilities__time_reversal_asymmetry_statistic__lag_3,Utilities__value_count__value_-1,Utilities__value_count__value_0,Utilities__value_count__value_1,Utilities__variance,Utilities__variance_larger_than_standard_deviation
id,,,,,,,,,,,,,,,,,,,,,
1,2.275874e+06,5280.10,-0.032620,-0.081992,0.032785,754.300000,-0.353553,-75.430000,115.221228,135.54,...,1.0,1.0,0.000000,0.000000e+00,0.000000,0.0,46.0,0.0,30105.446448,1.0
2,0.000000e+00,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,135.54,...,0.0,0.0,0.000000,0.000000e+00,0.000000,0.0,42.0,0.0,0.000000,0.0
3,3.345620e+04,736.20,-0.014780,-0.079622,0.021975,84.721429,-0.474342,-8.764286,7.274298,81.80,...,1.0,1.0,0.000000,-7.077717e+03,0.000000,0.0,53.0,0.0,1213.422604,1.0
4,0.000000e+00,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,135.54,...,1.0,1.0,0.000000,0.000000e+00,0.000000,0.0,33.0,0.0,12436.737122,1.0
5,1.668961e+06,6303.28,-0.000992,-0.100754,0.047146,363.488571,0.236351,27.460571,56.446830,558.80,...,1.0,1.0,0.000000,-7.755087e+05,0.000000,0.0,54.0,0.0,23318.130649,1.0
6,0.000000e+00,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,135.54,...,1.0,1.0,0.000000,0.000000e+00,0.000000,0.0,45.0,0.0,2996.817140,1.0
7,6.146560e+03,305.76,-0.018481,-0.035415,0.028704,25.872000,-0.124568,-1.176000,5.408085,135.54,...,0.0,0.0,0.000000,0.000000e+00,0.000000,0.0,47.0,0.0,0.000000,0.0
8,0.000000e+00,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,135.54,...,1.0,1.0,-633.572140,0.000000e+00,0.000000,0.0,44.0,0.0,176.153011,1.0
9,3.505602e+05,2201.76,-0.007936,-0.059934,0.023682,184.075714,-0.112253,-8.935714,35.374596,450.36,...,1.0,1.0,0.000000,0.000000e+00,0.000000,0.0,62.0,0.0,3587.105991,1.0
10,2.404118e+04,421.68,-0.016450,-0.040669,0.015731,48.048571,-0.167487,-5.163429,15.196662,135.54,...,1.0,1.0,0.000000,0.000000e+00,0.000000,0.0,51.0,0.0,14669.721600,1.0
11,0.000000e+00,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,...,1.0,1.0,0.000000,9.899815e+04,260837.243007,0.0,59.0,0.0,10443.904420,1.0
12,0.000000e+00,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,135.54,...,1.0,1.0,0.000000,-1.480918e+04,39024.183405,0.0,37.0,0.0,3830.687591,1.0
13,0.000000e+00,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,...,1.0,1.0,0.000000,0.000000e+00,0.000000,0.0,48.0,0.0,23525.133697,1.0
14,0.000000e+00,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,135.54,...,1.0,1.0,854.505194,0.000000e+00,-3246.478459,0.0,41.0,0.0,720.267854,1.0
15,0.000000e+00,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,135.54,...,1.0,1.0,0.000000,0.000000e+00,0.000000,0.0,47.0,0.0,18.921394,1.0
16,2.240423e+06,5952.18,-0.030601,-0.078205,0.017195,948.840000,-0.866025,-237.210000,79.070000,135.54,...,1.0,1.0,0.000000,0.000000e+00,0.000000,0.0,45.0,0.0,76800.667289,1.0
17,1.162145e+06,3112.00,-0.012174,-0.046046,0.016221,-88.914286,0.632456,88.914286,48.700360,622.40,...,1.0,1.0,0.000000,0.000000e+00,0.000000,0.0,64.0,0.0,28463.800338,1.0
18,0.000000e+00,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,...,1.0,1.0,0.000000,1.788426e+06,0.000000,0.0,66.0,0.0,47573.132544,1.0
19,1.302488e+05,721.80,-0.019349,-0.016543,0.000216,189.042857,-0.654654,-51.557143,29.766530,360.90,...,1.0,1.0,0.000000,0.000000e+00,540078.076291,0.0,51.0,0.0,8730.240636,1.0
20,2.112322e+05,919.20,-0.023230,-0.023485,0.000283,183.840000,-0.353553,-45.960000,70.205060,135.54,...,1.0,1.0,0.000000,0.000000e+00,0.000000,0.0,47.0,0.0,19311.688996,1.0